### ISSUE TITLE
Show Keys Label - Make user configurable

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/fusionpbx#4]
It would be helpful if the [Show Keys Label feature](https://github.com/fusionpbx/fusionpbx/blob/master/resources/templates/provision/grandstream/grp2615/%7B%24mac%7D.xml/#L7597) were configurable through a variable, and this was set to 1 by default.

**Comment by piajesse** [comment]
lets name it `grandstream_show_key_labels`, I'll start working on it right now

**Comment by piajesse** [comment]
P code is `P8386` for reference

**Comment by piajesse** [comment]
Merged with master
